config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  resources :topics do
    resources :bookmarks, except:[:index]
  end
  resources :bookmarks, except:[:index] do
      resources :likes , only: [:create, :destroy]
    end

  devise_for :users
  resources :users, only: [:update, :show]
  root to: 'welcome#index'

  get 'welcome/about'
  post :incoming, to: 'incoming#create'

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  validates :url, presence: true
  belongs_to :topic
  has_many :likes, dependent: :destroy
  after_create :set_embedly_url
  before_save :normalize_url
  
  private 
  
  def normalize_url
    self.url = url.include?("http://") ? url : "http://#{url}"
  end
  
  def set_embedly_url
  embedly_api = Embedly::API.new :key => ENV['EMBEDLY_API_KEY'],:maxwidth => 550,
  :wmode => 'transparent',
        :user_agent => 'Mozilla/5.0 (compatible; mytestapp/1.0; my@email.com)'

  Rails.logger.info ">>>> embedly object: #{embedly_api.inspect}"
    
    obj = embedly_api.extract :url => self.url
  # get result and find the attribute for the thumbnail_url
  # set the bookmark's thumbnail_url with that value -- update_attribute(thumbnail_url: val_of_thumbnail_url_from_response)
  o = obj.first
    if o.images != []
  image = o.images.first
  update_attribute(:thumbnail_url, image['url'])
    end
 end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :bookmark
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :title, presence: true
  validates_uniqueness_of :title
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :topics, dependent: :destroy
  has_many :likes, dependent: :destroy
  
  def liked(post)
    likes.where(bookmark_id: post.id).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  rescue_from Pundit::NotAuthorizedError do |exception|
   redirect_to root_url, alert: "You are not authorized to perform this action."
  end
  
   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :book_find, except: [:new, :create]
  respond_to :html, :js
  
  def book_find
    @bookmark = Bookmark.find(params[:id])
    @topic = Topic.find(params[:topic_id])
    authorize @bookmark
  end
  def destroy
    if @bookmark.destroy
      flash[:notice]= "Bookmark deleted"
    else
      flash[:error]= "Try again later"
    end
    respond_with(@bookmark) do |format|
       format.html { redirect_to @topic }
     end
  end
  
  

  def new
    @topic = Topic.find(params[:topic_id])
    @bookmark = @topic.bookmarks.new
    authorize @bookmark
  end
  
  def create
    @topic = Topic.find(params[:topic_id])
    @bookmark = @topic.bookmarks.new(bookmark_params)
    authorize @bookmark
    if @bookmark.save
      flash[:notice] = "Bookmark saved"
      redirect_to @topic
    else
      flash[:error] = "There was an error please try again"
      render :new
    end
  end
    

  def edit
  end
  
  def update
    if @bookmark.update_attributes(bookmark_params)
      flash[:notice]= "Bookmark Updated"
      redirect_to @topic
    else
      flash[:error]= "Try again later"
      render :edit
    end
  end
  private
  
  def bookmark_params
    params.require(:bookmark).permit(:url, :topic_id_id, :thumbnail_url)
  end
end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController

  # http://stackoverflow.com/questions/1177863/how-do-i-ignore-the-authenticity-token-for-specific-actions-in-rails
  skip_before_action :verify_authenticity_token, only: [:create]

  def create
    # Take a look at these in your server logs
    # to get a sense of what you're dealing with.
    puts "INCOMING PARAMS HERE: #{params}"
    @user = User.where(email: "#{params[:sender]}").last
    @topic = Topic.where(title: "#{params[:subject]}").last
    @url = params["body-plain"].gsub!(/\s/,'')
# check for syntax http://www.tutorialspoint.com/ruby/ruby_regular_expressions.htm

if @user != nil && @topic != nil
    @bookmark = @topic.bookmarks.new(url: @url)
   @bookmark.save!
elsif @user != nil && @topic == nil
  @t = Topic.create(title: "#{params[:subject]}", user_id: @user.id)
  @bookmark = @t.bookmarks.new(url: @url)
   @bookmark.save!
elsif @user == nil && @topic != nil
@u = User.new(email:"#{params[:sender]}", password: "password", password_confirmation: "password")
       @u.skip_confirmation!
       @u.save!
 @bookmark = @topic.bookmarks.new(url: @url)
   @bookmark.save!
else
@u = User.new(email:"#{params[:sender]}", password: "password", password_confirmation: "password")
       @u.skip_confirmation!
       @u.save!
 @t = Topic.create(title: "#{params[:subject]}", user_id: @u.id)
@bookmark = @t.bookmarks.new(url: @url)
   @bookmark.save!

end
 
    head 200
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  
  def create
    @bookmark = Bookmark.find(params[:bookmark_id])
    @topic = @bookmark.topic
    @like = current_user.likes.new(bookmark_id: @bookmark.id)
    if @like.save
      flash[:notice] = "Liked"
      redirect_to @topic
    else
      flash[:error] = "Try again"
      redirect_to @topic
    end
  end
  
  def destroy
    @bookmark = Bookmark.find(params[:bookmark_id])
    @topic = @bookmark.topic
    @like = Like.find(params[:id])
    if @like.destroy
      flash[:notice] = "Unliked"
      redirect_to @topic
    else
      flash[:error] = "Try again"
      redirect_to @topic
    end
  end
    
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :topic_find, except: [:new,:create,:index]
  def index
    @topics = Topic.all
  end
  
  def topic_find
    @topic = Topic.find(params[:id])
  end
    

  def show
    @bookmarks = @topic.bookmarks
  end
  
  def destroy
    if @topic.destroy
      flash[:notice]= "Tpoic was deleted"
      redirect_to topics_path
    else
      flash[:error] = "There was an error please try again"
      redirect_to @topic
    end
  end

  def new
    @topic = Topic.new
  end
  def create
    @user = current_user
    @topic =@user.topics.new(topic_params)
    if @topic.save
      flash[:notice]= "Your Topic is Created"
      redirect_to @topic
    else
      flash[:error] = "There was an error please try again"
      render :new
    end
  end
  
   def edit
   end
  
  def update
    if @topic.update_attributes(topic_params)
      redirect_to @topic
      flash[:notice] = "Topic was updated"
    else
      flash[:error] = "There was an error updating your topic. Please try again"
      render :edit
    end
  end
  
  private
  
  def topic_params
    params.require(:topic).permit(:title, :user_id)
  end

 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
    def update
     if current_user.update_attributes(user_params)
       flash[:notice] = "User information updated"
       redirect_to edit_user_registration_path
     else
       flash[:error] = "Invalid user information"
       redirect_to edit_user_registration_path
     end
   end
  
  def show
    @user = current_user
    @likes = current_user.likes
  end
  
  private
 
   def user_params
     params.require(:user).permit(:name)
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def name
    "Raymond"
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/destroy.js.erb
<% if @bookmark.destroyed? %>
   $('#bookmark-' +<%= @bookmark.id %>).hide();
 <% else %>
   $('#bookmark-' +<%= @bookmark.id %>).prepend("<div class='alert alert-danger'><%= flash[:error] %></div>");
 <% end %>

app/views/bookmarks/edit.html.erb
<h1>Edit Bookmark</h1>
<%= form_for [@topic, @bookmark] do |f| %>
<div class = "form-group">
  <%= f.label :url %>
  <%= f.text_area :url, class: 'form-control', placeholder: "Enter URL" %>
</div>
<%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>
<%= form_for [@topic, @bookmark] do |f| %>
<div class = "form-group">
  <%= f.label :url %>
  <%= f.text_area :url, class: 'form-control', placeholder: "Enter URL" %>
</div>
<%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>

app/views/bookmarks/show.html.erb
<h1>Bookmarks#show</h1>
<p>Find me in app/views/bookmarks/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmarks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class = "container" >
    <ul class = "nav nav-tabs" >
      <li><%= link_to "About", welcome_about_path %></li>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Topics", topics_path %></li>
      <% if current_user %>
      <li><%= link_to "My Bookmarks", user_path(current_user.id) %></li>
      <%end%>
      <div class = "pull-right user-info" >
        <% if current_user %>
        Hello <%= link_to (current_user.name || current_user.email), current_user %>!
        <%= link_to edit_user_registration_path, class: 'btn btn-primary btn-sm', title: "Profile History" do %>
              <span class="glyphicon glyphicon-user"></span>
            <% end %>
        <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-sm', title: "Sign Out" do %>
              <span class="glyphicon glyphicon-log-out"></span>
            <% end %>
        <% else%>
        <%= link_to "Sign in", new_user_session_path %> or
        <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
    </ul>
    <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:error] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:error] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>

<%= yield %>
  </div>

</body>
</html>

app/views/likes/_like.html.erb
<% if like = current_user.liked(bookmark) %>
    <%= link_to [bookmark, like], class: 'btn btn-danger', method: :delete do %>
      <i class="glyphicon glyphicon-star-empty"> </i>&nbsp; Unlike
    <% end %>
  <% else %>
    <%= link_to [bookmark, Like.new], class: 'btn btn-primary', method: :post do %>
      <i class="glyphicon glyphicon-star"> </i>&nbsp; Like
    <% end %>
  <% end %>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>
<%= form_for @topic do |f| %>
<div class = "form-group">
  <%= f.label :Title %>
  <%= f.text_area :title, class: 'form-control', placeholder: "Enter topic title" %>
</div>
<%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>

app/views/topics/index.html.erb
<h1>Topics</h1>
<%= link_to "New Topic", new_topic_path, class:"btn btn-success" %>
<% @topics.each do |topic| %>
 <div class="row">
  <div class="col-md-8">
      <h2><%= link_to topic.title, topic_path(topic) %></h2>
   </div>
</div>
<div class="row">
   <% topic.bookmarks.each do |bookmark| %>
     <div class="col-md-3">
       <br><div class="bookmark_container">
      <div class="thumbnail">
       <% link_text = bookmark.thumbnail_url.present? ? "<img src='#{bookmark.thumbnail_url}'/>".html_safe : bookmark.url %>
    <%= link_to link_text, "#{bookmark.url}", target: "_blank"%> 
    </div>
  </div>
     </div>

   <%end%>
  </div>
    <%end%>
    

app/views/topics/new.html.erb
<h1>New Topic</h1>
<%= form_for @topic do |f| %>
<div class = "form-group">
  <%= f.label :Title %>
  <%= f.text_area :title, class: 'form-control', placeholder: "Enter topic title" %>
</div>
<%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>

app/views/topics/show.html.erb
<h1><%= @topic.title %></h1>
<%= link_to "Edit", edit_topic_path(@topic), class:"btn btn-success" %>
<%= link_to "Delete", @topic_path, method: :delete, class:"btn btn-danger", data: { confirm: 'Are you sure you want to delete this topic?' } %>
<%= link_to "Add Bookmark", new_topic_bookmark_path(@topic,@bookmark), class:"btn btn-warning" %>

<div class="row"><br>
<% @topic.bookmarks.each do |bookmark| %>
  
<div class="col-md-3">
  <%= content_tag :div, id: "bookmark-#{bookmark.id}" do %>
  <br><div class="bookmark_container">
      <div class="thumbnail">
       <% link_text = bookmark.thumbnail_url.present? ? "<img src='#{bookmark.thumbnail_url}'/>".html_safe : bookmark.url %>
        <%= link_to link_text, bookmark.url, target: "_blank" %> 
    </div>
  </div><br>
  <%= render partial: 'likes/like', locals: { bookmark: bookmark } %>
  <%= link_to "Edit", edit_topic_bookmark_path(@topic, bookmark), class:"btn btn-success" %>
  <%= link_to "Delete", topic_bookmark_path(@topic,bookmark), method: :delete, class:"btn btn-danger", data: { confirm: 'Are you sure you want to delete this bookmark?' }, remote: true %>
  <%end%>
     </div>
  <%end%>
</div><br>

app/views/users/show.html.erb
<h1>My Bookmarks</h1>
<% @likes.pluck(:bookmark_id).each do |id| %>
<div class="row">
<h2 style="color:green"><em><%= link_to "#{Bookmark.find(id).url}", Bookmark.find(id).url %></em></h2>
</div>
<%end%>

<% @user.topics.pluck(:id).each do |topid| %>
 <% Topic.find(topid).bookmarks.each do |bookmark| %>
   <% unless @likes.pluck(:bookmark_id).include? bookmark.id %>
<div class="row">
  <h2 style="color:green"><%= link_to "#{bookmark.url}", bookmark.url %></h2>
  <small>Source Topic <%= link_to "#{Topic.find(topid).title}", topic_path(topid)  %></small>
</div>

   <%end%>
 <%end%>
<%end%>

app/views/welcome/about.html.erb
<h1>About</h1>
<p>Created by <%= name %></p>

app/views/welcome/index.html.erb
<br/>
<div class="jumbotron">
  <h1>Blocmarks</h1>
  <p>Where you can share your favorite Bookmarks with your friends</p>
  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or 
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
  </p>
</div>

<div class="row">
  <div class="col-md-4">
    <h2>As easy as sending an email.</h2>
    <p>Either from your computer or cell phone just send your Bookmark and it will be shared instantly!.</p>
  </div>
  <div class="col-md-4">
    <h2>The best in every topic of your life!</h2>
    <p>Blocmarks is the center where all users share the best bookmarks they encountered.</p>
  </div>
  <div class="col-md-4">
    <h2>You will find what you are looking for.</h2>
    <p>Shopping Food Restaurants and much more!</p>
  </div>
</div>